### ISSUE TITLE
Doc: Getting Started

### ISSUE THREAD

**Issue by techie66** [techie66/EngineDataLogger#11]
Need to make "Getting Started" documentation. 
Ideally it will cover all the basics to start using this software from scratch, how to add other components (dashboard, front_controls, etc) and a good discussion on config options.

**Comment by techie66** [comment]
Start using Doxygen for documentation of overall program.

**Comment by techie66** [comment]
Started the [Wiki](https://github.com/techie66/EngineDataLogger/wiki).

**Comment by kurt-k3po** [comment]
I would like to help with the "Getting started" documentation and document my steps. How can I do that?

**Comment by techie66** [comment]
I have just enabled wiki editing for everyone. Thank you for your assistance.

**Comment by techie66** [comment]
Wiki is live, no need for this issue to still be open.
