### ISSUE TITLE
Option to log Servo TPS as "IAP"

### ISSUE THREAD

**Issue by techie66** [techie66/EngineDataLogger#12]
I want the option to pretend that the SERVO_mV is actually coming from a MAP sensor and interpret it as such

Need options to set low/high mV and to enable the feature. Simple linear mapping of mV to kPa.

**Comment by ivanzanzani** [comment]
Awesome work 
Ivan

**Comment by techie66** [comment]
@ivanzanzani It is working "mostly" well. Found a bug inlibIgnitech. Contact me and I can help you get started trying it out.
