### ISSUE TITLE
main.cpp log_data.advance1

### ISSUE THREAD

**Issue by kurt-k3po** [techie66/EngineDataLogger#24]
https://github.com/techie66/EngineDataLogger/blob/6fd558a3b81a8d96990f3efae44e770ee6c244f1/src/main.cpp#L445-L452

I think, there is something screwed up with log_data.advance1.  Shoud be log_data.advance1 .... 4 at lines 449 - 452

Right?

**Comment by techie66** [comment]
absolutely! I thought I had fixed that already.  I'll get a fix pushed soon to the development branch. I'll also push the patch to feature-can.

**Comment by techie66** [comment]
Please confirm fixed.

**Comment by kurt-k3po** [comment]
pulled. I can confirm the fix
