### ISSUE TITLE
typo in enginedatalogger.service

### ISSUE THREAD

**Issue by kurt-k3po** [techie66/EngineDataLogger#25]
In the result a typo in `/lib/systemd/system/enginedatalogger.service` prevents automatic start after boot,

`systemd[1]: /lib/systemd/system/enginedatalogger.service:10: Unknown lvalue 'WantedBy' in section 'Service', ignoring`

Found this in source 

https://github.com/techie66/EngineDataLogger/blob/65a44eaa3cc3ba6f8d655996624b4b302222ee7f/etc/enginedatalogger.service.in#L14

'#' in front of section '[Install]' should be removed. 

Please check, if this is the right and only place which have to be corrected

**Comment by techie66** [comment]
I'll leave this open until you can confirm that the issue is fixed.

**Comment by kurt-k3po** [comment]
Fix confirmed.
