### ISSUE TITLE
typo in main.cpp leads to wrong lambda value in logfile (Ignitech WB2)

### ISSUE THREAD

**Issue by kurt-k3po** [techie66/EngineDataLogger#26]
loged lambda value is 10th to small

https://github.com/techie66/EngineDataLogger/blob/65a44eaa3cc3ba6f8d655996624b4b302222ee7f/src/main.cpp#L848
shoud be `fprintf(fd_log,"%.2f,",log_data.lambda/100.0);`

**Comment by techie66** [comment]
Simple change. commited to feature-can branch
